/**
 * Border character set definitions
 */
import type { BoxChars, BorderStyle } from '../types.js';

/** Character set for each border style */
export const BORDER_CHARS: Record<BorderStyle, BoxChars> = {
  rounded: {
    topLeft: '╭',
    topRight: '╮',
    bottomLeft: '╰',
    bottomRight: '╯',
    horizontal: '─',
    vertical: '│',
    topMid: '┬',
    bottomMid: '┴',
    midLeft: '├',
    midRight: '┤',
    mid: '─',
    midMid: '┼',
  },
  heavy: {
    topLeft: '┏',
    topRight: '┓',
    bottomLeft: '┗',
    bottomRight: '┛',
    horizontal: '━',
    vertical: '┃',
    topMid: '┳',
    bottomMid: '┻',
    midLeft: '┣',
    midRight: '┫',
    mid: '━',
    midMid: '╋',
  },
  double: {
    topLeft: '╔',
    topRight: '╗',
    bottomLeft: '╚',
    bottomRight: '╝',
    horizontal: '═',
    vertical: '║',
    topMid: '╦',
    bottomMid: '╩',
    midLeft: '╠',
    midRight: '╣',
    mid: '═',
    midMid: '╬',
  },
  ascii: {
    topLeft: '+',
    topRight: '+',
    bottomLeft: '+',
    bottomRight: '+',
    horizontal: '-',
    vertical: '|',
    topMid: '+',
    bottomMid: '+',
    midLeft: '+',
    midRight: '+',
    mid: '-',
    midMid: '+',
  },
  simple: {
    topLeft: ' ',
    topRight: ' ',
    bottomLeft: ' ',
    bottomRight: ' ',
    horizontal: '─',
    vertical: ' ',
    topMid: ' ',
    bottomMid: ' ',
    midLeft: ' ',
    midRight: ' ',
    mid: '─',
    midMid: ' ',
  },
  minimal: {
    topLeft: ' ',
    topRight: ' ',
    bottomLeft: ' ',
    bottomRight: ' ',
    horizontal: '─',
    vertical: ' ',
    topMid: '─',
    bottomMid: '─',
    midLeft: ' ',
    midRight: ' ',
    mid: '─',
    midMid: '─',
  },
  horizontals: {
    topLeft: '─',
    topRight: '─',
    bottomLeft: '─',
    bottomRight: '─',
    horizontal: '─',
    vertical: ' ',
    topMid: '─',
    bottomMid: '─',
    midLeft: '─',
    midRight: '─',
    mid: '─',
    midMid: '─',
  },
  markdown: {
    topLeft: '|',
    topRight: '|',
    bottomLeft: '|',
    bottomRight: '|',
    horizontal: '-',
    vertical: '|',
    topMid: '|',
    bottomMid: '|',
    midLeft: '|',
    midRight: '|',
    mid: '-',
    midMid: '|',
  },
  none: {
    topLeft: ' ',
    topRight: ' ',
    bottomLeft: ' ',
    bottomRight: ' ',
    horizontal: ' ',
    vertical: ' ',
    topMid: ' ',
    bottomMid: ' ',
    midLeft: ' ',
    midRight: ' ',
    mid: ' ',
    midMid: ' ',
  },
};
